name: Feature Request
description: Suggest a new feature or enhancement for Chess Viewer
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees:
  - BilgeGates

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature! 💡
        Please provide detailed information about your feature request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - Board Rendering
        - FEN/PGN Support
        - Export/Import
        - UI/UX Improvement
        - Customization Options
        - Performance
        - Accessibility
        - Mobile Support
        - Annotation Tools
        - Integration/API
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my work)
        - High (Very important)
        - Medium (Would be nice to have)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        As a chess coach, I want to...
        So that I can...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: Provide examples, mockups, or references from other applications
      placeholder: |
        - Link to similar feature in other apps
        - Upload mockup images
        - Describe expected behavior

  - type: checkboxes
    id: target-users
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      options:
        - label: Chess players
        - label: Chess coaches
        - label: Content creators
        - label: Book authors
        - label: Tournament organizers
        - label: Students/learners
        - label: Developers
        - label: All users

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is to implement?
      options:
        - Simple (Small change, quick implementation)
        - Medium (Moderate effort required)
        - Complex (Significant development needed)
        - I don't know

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute to implementing this feature
        - label: I can help with testing this feature
        - label: I can provide additional design/mockups

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing feature requests to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have provided sufficient detail for the feature to be understood
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: Any additional information...
